### ISSUE TITLE
CAP: Stargate conflict (a quite interesting one)

### ISSUE THREAD

**Issue by VelonacepsCalyxEggs** [Blu-x92/LUNA_SWORD_COMBAT_SYSTEM#2] opened 2022-07-30 18:09 UTC
**Hello there!** 
So, I got this addon lately, it's a great one not gonna lie, but I noticed that shield emmiters from Carter's addon Pack (which is a quite old addon that was working for a long time without any trouble) stopped blocking hitscan weapons once I enabled this addon. Does this addon tamper with hitscan weapons somehow? 
Is there a chance you will look into this? 

Edit: 
Here's a video of it in action: 
https://youtu.be/J-5v1U5i7lc

**Comment by Blu-x92** [comment] 2022-07-30 18:42
Give me link to addon i try to add a workaround but i can not promise anything. It's a known problem with how gmod handles FireBullets which by design makes addons conflict with each other if they have to hook into that function

**Comment by VelonacepsCalyxEggs** [comment] 2022-07-30 19:15
> Give me link to addon i try to add a workaround but i can not promise anything. It's a known problem with how gmod handles FireBullets which by design makes addons conflict with each other if they have to hook into that function

Here you go, 1st one is the collection, 2nd one is the Code (which is the only thing you'll probably need.)
https://steamcommunity.com/workshop/filedetails/?id=180077636
https://steamcommunity.com/sharedfiles/filedetails/?id=175394472

**Comment by Blu-x92** [comment] 2022-07-31 08:06
should be fixed

**Comment by VelonacepsCalyxEggs** [comment] 2022-07-31 13:16
> should be fixed

Thank you!

**Comment by VelonacepsCalyxEggs** [comment] 2022-07-31 13:20
> should be fixed

So, I tested it, the bullets are detected by the shield, however they still pass through it. Still, I appreciate you did everything you could.

**Comment by VelonacepsCalyxEggs** [comment] 2022-07-31 13:23
> should be fixed

I can contact AlexALX (person currently maintaining CAP) and ask him if he can do anything. If you are sure you can do nothing on your side.

**Comment by Blu-x92** [comment] 2022-07-31 14:25
o hold on probably just a simple logic mistake

**Comment by Blu-x92** [comment] 2022-07-31 14:34
is it fixed now?

**Comment by VelonacepsCalyxEggs** [comment] 2022-07-31 16:16
> is it fixed now?

Indeed it is! Thank you!

**Closed** 2022-07-31 16:55 UTC
